# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/pynq_z2/project/z2_dev/.Xil/Vivado-36400-yi/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z020clg400-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ipshared/ec67/hdl {
      C:/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ipshared/ec67/hdl {
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_aw_atc.v
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_b_atc.v
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_w_atc.v
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_atc.v
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_trace_buffer.v
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_processing_system7_0_0/hdl/verilog/processing_system7_v5_5_processing_system7.v
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_processing_system7_0_0/synth/system_processing_system7_0_0.v
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ipshared/0a3f/hdl/axi_register_slice_v2_1_vl_rfs.v
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ipshared/5390/hdl/axi_data_fifo_v2_1_vl_rfs.v
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ipshared/3fa0/hdl/axi_crossbar_v2_1_vl_rfs.v
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_xbar_1/synth/system_xbar_1.v
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_xbar_2/synth/system_xbar_2.v
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_xbar_3/synth/system_xbar_3.v
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0.v
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ipshared/90c8/hdl/axi_protocol_converter_v2_1_vl_rfs.v
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_auto_pc_0/synth/system_auto_pc_0.v
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_auto_pc_1/synth/system_auto_pc_1.v
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_auto_pc_2/synth/system_auto_pc_2.v
    }
      rt::read_verilog -include d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ipshared/ec67/hdl {
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/synth/system.v
      D:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/hdl/system_wrapper.v
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::read_vhdl -lib lib_cdc_v1_0_2 d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_13 d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib {
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_rst_ps7_0_50M_0/synth/system_rst_ps7_0_50M_0.vhd
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_microblaze_0_0/synth/system_microblaze_0_0.vhd
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_dlmb_v10_0/synth/system_dlmb_v10_0.vhd
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_ilmb_v10_0/synth/system_ilmb_v10_0.vhd
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_dlmb_bram_if_cntlr_0/synth/system_dlmb_bram_if_cntlr_0.vhd
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_ilmb_bram_if_cntlr_0/synth/system_ilmb_bram_if_cntlr_0.vhd
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_lmb_bram_0/synth/system_lmb_bram_0.vhd
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_mdm_1_0/synth/system_mdm_1_0.vhd
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_axi_gpio_0_0/synth/system_axi_gpio_0_0.vhd
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_axi_gpio_1_0/synth/system_axi_gpio_1_0.vhd
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_axi_gpio_2_0/synth/system_axi_gpio_2_0.vhd
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_axi_uartlite_0_0/synth/system_axi_uartlite_0_0.vhd
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_axi_bram_ctrl_0_0/synth/system_axi_bram_ctrl_0_0.vhd
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_blk_mem_gen_0_0/synth/system_blk_mem_gen_0_0.vhd
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_wiz_0_0_conv_funs_pkg.vhd
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_wiz_0_0_proc_common_pkg.vhd
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_wiz_0_0_ipif_pkg.vhd
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_wiz_0_0_family_support.vhd
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_wiz_0_0_family.vhd
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_wiz_0_0_soft_reset.vhd
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_wiz_0_0_pselect_f.vhd
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_xadc_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_xadc_wiz_0_0_address_decoder.vhd
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_xadc_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_xadc_wiz_0_0_slave_attachment.vhd
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_xadc_wiz_0_0/interrupt_control_v2_01_a/hdl/src/vhdl/system_xadc_wiz_0_0_interrupt_control.vhd
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_xadc_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_xadc_wiz_0_0_axi_lite_ipif.vhd
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0_xadc_core_drp.vhd
      d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0_axi_xadc.vhd
    }
      rt::read_vhdl -lib microblaze_v11_0_9 d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ipshared/057e/hdl/microblaze_v11_0_vh_rfs.vhd
      rt::read_vhdl -lib lmb_v10_v3_0_12 d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ipshared/cd1d/hdl/lmb_v10_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib lmb_bram_if_cntlr_v4_0_21 d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ipshared/a177/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd
      rt::read_vhdl -lib blk_mem_gen_v8_4_5 d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ipshared/25a8/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib axi_lite_ipif_v3_0_4 d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib mdm_v3_2_23 d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ipshared/b8f4/hdl/mdm_v3_2_vh_rfs.vhd
      rt::read_vhdl -lib interrupt_control_v3_1_4 d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd
      rt::read_vhdl -lib axi_gpio_v2_0_28 d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ipshared/3ed9/hdl/axi_gpio_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_2_7 d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ipshared/83df/hdl/fifo_generator_v13_2_vhsyn_rfs.vhd
      rt::read_vhdl -lib lib_pkg_v1_0_2 d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd
      rt::read_vhdl -lib lib_srl_fifo_v1_0_2 d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd
      rt::read_vhdl -lib axi_uartlite_v2_0_30 d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ipshared/5d2b/hdl/axi_uartlite_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib axi_bram_ctrl_v4_1_6 d:/pynq_z2/project/z2_dev/z2_dev.gen/sources_1/bd/system/ipshared/3c31/hdl/axi_bram_ctrl_v4_1_rfs.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top system_wrapper
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    set_param edifin.funnel true
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "D:/pynq_z2/project/z2_dev/.Xil/Vivado-36400-yi/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
