# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/zynq/pm_test/pm_test.srcs/sources_1/bd/pm_zynq/ip/pm_zynq_xbar_0/pm_zynq_xbar_0.xci
# IP: The module: 'pm_zynq_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/zynq/pm_test/pm_test.gen/sources_1/bd/pm_zynq/ip/pm_zynq_xbar_0/pm_zynq_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pm_zynq_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/zynq/pm_test/pm_test.srcs/sources_1/bd/pm_zynq/ip/pm_zynq_xbar_0/pm_zynq_xbar_0.xci
# IP: The module: 'pm_zynq_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/zynq/pm_test/pm_test.gen/sources_1/bd/pm_zynq/ip/pm_zynq_xbar_0/pm_zynq_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pm_zynq_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
