# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/project/zynq/pm_test/pm_test.srcs/sources_1/bd/pm_zynq/ip/pm_zynq_axi_gpio_1_0/pm_zynq_axi_gpio_1_0.xci
# IP: The module: 'pm_zynq_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/project/zynq/pm_test/pm_test.gen/sources_1/bd/pm_zynq/ip/pm_zynq_axi_gpio_1_0/pm_zynq_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pm_zynq_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/project/zynq/pm_test/pm_test.gen/sources_1/bd/pm_zynq/ip/pm_zynq_axi_gpio_1_0/pm_zynq_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pm_zynq_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/project/zynq/pm_test/pm_test.gen/sources_1/bd/pm_zynq/ip/pm_zynq_axi_gpio_1_0/pm_zynq_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pm_zynq_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/project/zynq/pm_test/pm_test.srcs/sources_1/bd/pm_zynq/ip/pm_zynq_axi_gpio_1_0/pm_zynq_axi_gpio_1_0.xci
# IP: The module: 'pm_zynq_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/project/zynq/pm_test/pm_test.gen/sources_1/bd/pm_zynq/ip/pm_zynq_axi_gpio_1_0/pm_zynq_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pm_zynq_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/project/zynq/pm_test/pm_test.gen/sources_1/bd/pm_zynq/ip/pm_zynq_axi_gpio_1_0/pm_zynq_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pm_zynq_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/project/zynq/pm_test/pm_test.gen/sources_1/bd/pm_zynq/ip/pm_zynq_axi_gpio_1_0/pm_zynq_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pm_zynq_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
